pipeline {
  agent {
    docker { image 'maven:3.9.10-sapmachine-17' }
  }

  environment {
    IMAGE_NAME           = 'demo-github-app'
    REGISTRY_CREDENTIALS = 'dockerhub-creds'

    SONAR_HOST_URL       = 'http://192.168.136.143:9000'
    SONAR_TOKEN          = 'sqp_9e0f3e0d01fd72157292068f7964dad8a9f7'
    SONAR_PROJECT_KEY    = 'EvanBlaise'
    SONAR_PROJECT_NAME   = 'EvanBlaise'
    SONAR_SOURCES        = 'src/main/java'
    SONAR_JAVA_BINARIES  = 'target/classes'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Test') {
      steps {
        dir('demo-github') {
          sh 'mvn clean package'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('demo-github') {
          sh "mvn sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_TOKEN}"
        }
      }
    }

    stage('Docker Build') {
      steps {
        script {
          docker.build(IMAGE_NAME, 'demo-github/')
        }
      }
    }

    stage('Docker Push') {
      steps {
        script {
          docker.withRegistry('', REGISTRY_CREDENTIALS) {
            docker.image(IMAGE_NAME).push()
          }
        }
      }
    }
  }
}
